services:
  mysql:
    image: mysql:8.0
    container_name: fomo-mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/:/home/

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: fomo-php
    ports:
      - "9000:9000"
    expose:
      - 9000
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./app:/app/
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/php-cli.ini:/usr/local/etc/php/php-cli.ini
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - mysql

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: fomo-nginx
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ./app:/app
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  redis:
    image: redis:latest
    container_name: fomo-redis
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis/redis.conf:/etc/redis/redis.conf
      - ./docker/redis/data:/data
    depends_on:
      - mysql

networks:
  default:
    driver: bridge