security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        users_in_memory: { memory: null }
        store_provider:
            id: App\Security\StoreUserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        sse:
            pattern: ^/sse
            stateless: true
            provider: store_provider
            jwt: ~
            #pattern: ^/sse
            #stateless: true  # Uncomment if the SSE should be stateless
            # If authentication is required, configure as needed:
            # http_basic: ~  # Or any other authentication mechanism
            #security: false  # Public access without authentication
        login:
            pattern: ^/api/token
            stateless: true
            provider: store_provider
            custom_authenticators:
                - App\Security\StoreAuthTokenAuthenticator
            json_login:
                check_path: /api/token
                provider: store_provider
        api:
            pattern: ^/api
            stateless: true
            provider: store_provider
            jwt: ~
        main:
            lazy: true
            stateless: false
            provider: store_provider
            custom_authenticator: App\Security\StoreAuthTokenAuthenticator

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    access_control:
        - { path: ^/api/token, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: ROLE_STORE }

#    enable_authenticator_manager: true

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon